# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineOJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('submitted', models.PositiveIntegerField(default=0)),
                ('accepted', models.PositiveIntegerField(default=0)),
                ('submitted_on_oringin', models.PositiveIntegerField(default=0)),
                ('accepted_on_oringin', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=50)),
                ('time_limit', models.CharField(max_length=20)),
                ('mem_limit', models.CharField(max_length=20)),
                ('detail', models.CharField(max_length=2000)),
                ('sample', models.CharField(max_length=1000)),
                ('oj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OJ.OnlineOJ')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('time', models.PositiveIntegerField(default=0)),
                ('mem', models.PositiveIntegerField(default=0)),
                ('lan', models.CharField(max_length=50)),
                ('codelength', models.PositiveIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OJ.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountname', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('accepted', models.PositiveIntegerField(default=0)),
                ('submitted', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OJ.User'),
        ),
    ]
