# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0002_auto_20161114_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='mem_limit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
