# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0005_auto_20161212_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblemstatus',
            name='laststatus',
            field=models.CharField(default=b'Unsubmitted', max_length=100),
        ),
        migrations.AlterField(
            model_name='contestlog',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contestproblemstatus',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
