# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0006_auto_20161212_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='source',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='contestproblemstatus',
            name='endtime',
            field=models.DateTimeField(blank=True),
        ),
    ]
